# This workflow runs the CMake and Premake tests
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # premake tests
  premake_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Setups the premake build system
      - name: Setup premake
        # You may pin to the exact commit or the version.
        # uses: abel0b/setup-premake@b80dc6f70e8ab159fb854bdadbeb1a53cfc28723
        uses: abel0b/setup-premake@v2.4
        with:
          # Premake version
          version: "5.0.0-beta2"
          # Premake path
          #path: # optional, default is .premake

      # Runs a set of commands using the runners shell
      - name: Test
        run: |
          cd premake
          premake5 --file=run_tests.lua self-test
  # cmake tests
  cmake_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Run cmake tests
      - name: Configure Project
        run: |
          cmake -Hcmake/tests/ -Bbuild

      - name: Run Unit Tests
        run: |
          cd build
          ctest -j 2 --output-on-failure